services:
  - type: web
    name: backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - fromFile: .env

  - type: web
    name: frontend
    env: node
    buildCommand: cd eliteedifice && npm install
    startCommand: cd eliteedifice && npm start
    envVars:
      - key: NODE_ENV
        value: production